version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/scala-3.3.1/aws-lambda-zio-scala-assembly-0.1.0-SNAPSHOT.jar
